# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seqr_query_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='seqr_query_service.proto',
  package='seqr',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18seqr_query_service.proto\x12\x04seqr\"\x8f\x05\n\x0cQueryRequest\x12\x12\n\narrow_urls\x18\x01 \x03(\t\x12\x1a\n\x12projection_columns\x18\x02 \x03(\t\x12\x38\n\x11\x66ilter_expression\x18\x03 \x01(\x0b\x32\x1d.seqr.QueryRequest.Expression\x12\x10\n\x08max_rows\x18\x04 \x01(\x05\x1a\x82\x04\n\nExpression\x12\x10\n\x06\x63olumn\x18\x01 \x01(\tH\x00\x12\x38\n\x07literal\x18\x02 \x01(\x0b\x32%.seqr.QueryRequest.Expression.LiteralH\x00\x12\x32\n\x04\x63\x61ll\x18\x03 \x01(\x0b\x32\".seqr.QueryRequest.Expression.CallH\x00\x1a\x9c\x01\n\x07Literal\x12\x14\n\nbool_value\x18\x01 \x01(\x08H\x00\x12\x15\n\x0bint32_value\x18\x02 \x01(\x05H\x00\x12\x15\n\x0bint64_value\x18\x03 \x01(\x03H\x00\x12\x15\n\x0b\x66loat_value\x18\x04 \x01(\x02H\x00\x12\x16\n\x0c\x64ouble_value\x18\x05 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x06 \x01(\tH\x00\x42\x06\n\x04type\x1a\xa8\x01\n\x04\x43\x61ll\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x30\n\targuments\x18\x02 \x03(\x0b\x32\x1d.seqr.QueryRequest.Expression\x12L\n\x12set_lookup_options\x18\x03 \x01(\x0b\x32..seqr.QueryRequest.Expression.SetLookupOptionsH\x00\x42\t\n\x07options\x1a\"\n\x10SetLookupOptions\x12\x0e\n\x06values\x18\x01 \x03(\tB\x06\n\x04type\"9\n\rQueryResponse\x12\x10\n\x08num_rows\x18\x01 \x01(\x05\x12\x16\n\x0erecord_batches\x18\x02 \x01(\x0c\x32\x42\n\x0cQueryService\x12\x32\n\x05Query\x12\x12.seqr.QueryRequest\x1a\x13.seqr.QueryResponse\"\x00\x62\x06proto3'
)




_QUERYREQUEST_EXPRESSION_LITERAL = _descriptor.Descriptor(
  name='Literal',
  full_name='seqr.QueryRequest.Expression.Literal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bool_value', full_name='seqr.QueryRequest.Expression.Literal.bool_value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int32_value', full_name='seqr.QueryRequest.Expression.Literal.int32_value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int64_value', full_name='seqr.QueryRequest.Expression.Literal.int64_value', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='float_value', full_name='seqr.QueryRequest.Expression.Literal.float_value', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='double_value', full_name='seqr.QueryRequest.Expression.Literal.double_value', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='string_value', full_name='seqr.QueryRequest.Expression.Literal.string_value', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='seqr.QueryRequest.Expression.Literal.type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=319,
  serialized_end=475,
)

_QUERYREQUEST_EXPRESSION_CALL = _descriptor.Descriptor(
  name='Call',
  full_name='seqr.QueryRequest.Expression.Call',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='function_name', full_name='seqr.QueryRequest.Expression.Call.function_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arguments', full_name='seqr.QueryRequest.Expression.Call.arguments', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_lookup_options', full_name='seqr.QueryRequest.Expression.Call.set_lookup_options', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='options', full_name='seqr.QueryRequest.Expression.Call.options',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=478,
  serialized_end=646,
)

_QUERYREQUEST_EXPRESSION_SETLOOKUPOPTIONS = _descriptor.Descriptor(
  name='SetLookupOptions',
  full_name='seqr.QueryRequest.Expression.SetLookupOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='seqr.QueryRequest.Expression.SetLookupOptions.values', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=648,
  serialized_end=682,
)

_QUERYREQUEST_EXPRESSION = _descriptor.Descriptor(
  name='Expression',
  full_name='seqr.QueryRequest.Expression',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='column', full_name='seqr.QueryRequest.Expression.column', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='literal', full_name='seqr.QueryRequest.Expression.literal', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='call', full_name='seqr.QueryRequest.Expression.call', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_QUERYREQUEST_EXPRESSION_LITERAL, _QUERYREQUEST_EXPRESSION_CALL, _QUERYREQUEST_EXPRESSION_SETLOOKUPOPTIONS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='seqr.QueryRequest.Expression.type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=176,
  serialized_end=690,
)

_QUERYREQUEST = _descriptor.Descriptor(
  name='QueryRequest',
  full_name='seqr.QueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='arrow_urls', full_name='seqr.QueryRequest.arrow_urls', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='projection_columns', full_name='seqr.QueryRequest.projection_columns', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter_expression', full_name='seqr.QueryRequest.filter_expression', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_rows', full_name='seqr.QueryRequest.max_rows', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_QUERYREQUEST_EXPRESSION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=690,
)


_QUERYRESPONSE = _descriptor.Descriptor(
  name='QueryResponse',
  full_name='seqr.QueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_rows', full_name='seqr.QueryResponse.num_rows', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='record_batches', full_name='seqr.QueryResponse.record_batches', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=692,
  serialized_end=749,
)

_QUERYREQUEST_EXPRESSION_LITERAL.containing_type = _QUERYREQUEST_EXPRESSION
_QUERYREQUEST_EXPRESSION_LITERAL.oneofs_by_name['type'].fields.append(
  _QUERYREQUEST_EXPRESSION_LITERAL.fields_by_name['bool_value'])
_QUERYREQUEST_EXPRESSION_LITERAL.fields_by_name['bool_value'].containing_oneof = _QUERYREQUEST_EXPRESSION_LITERAL.oneofs_by_name['type']
_QUERYREQUEST_EXPRESSION_LITERAL.oneofs_by_name['type'].fields.append(
  _QUERYREQUEST_EXPRESSION_LITERAL.fields_by_name['int32_value'])
_QUERYREQUEST_EXPRESSION_LITERAL.fields_by_name['int32_value'].containing_oneof = _QUERYREQUEST_EXPRESSION_LITERAL.oneofs_by_name['type']
_QUERYREQUEST_EXPRESSION_LITERAL.oneofs_by_name['type'].fields.append(
  _QUERYREQUEST_EXPRESSION_LITERAL.fields_by_name['int64_value'])
_QUERYREQUEST_EXPRESSION_LITERAL.fields_by_name['int64_value'].containing_oneof = _QUERYREQUEST_EXPRESSION_LITERAL.oneofs_by_name['type']
_QUERYREQUEST_EXPRESSION_LITERAL.oneofs_by_name['type'].fields.append(
  _QUERYREQUEST_EXPRESSION_LITERAL.fields_by_name['float_value'])
_QUERYREQUEST_EXPRESSION_LITERAL.fields_by_name['float_value'].containing_oneof = _QUERYREQUEST_EXPRESSION_LITERAL.oneofs_by_name['type']
_QUERYREQUEST_EXPRESSION_LITERAL.oneofs_by_name['type'].fields.append(
  _QUERYREQUEST_EXPRESSION_LITERAL.fields_by_name['double_value'])
_QUERYREQUEST_EXPRESSION_LITERAL.fields_by_name['double_value'].containing_oneof = _QUERYREQUEST_EXPRESSION_LITERAL.oneofs_by_name['type']
_QUERYREQUEST_EXPRESSION_LITERAL.oneofs_by_name['type'].fields.append(
  _QUERYREQUEST_EXPRESSION_LITERAL.fields_by_name['string_value'])
_QUERYREQUEST_EXPRESSION_LITERAL.fields_by_name['string_value'].containing_oneof = _QUERYREQUEST_EXPRESSION_LITERAL.oneofs_by_name['type']
_QUERYREQUEST_EXPRESSION_CALL.fields_by_name['arguments'].message_type = _QUERYREQUEST_EXPRESSION
_QUERYREQUEST_EXPRESSION_CALL.fields_by_name['set_lookup_options'].message_type = _QUERYREQUEST_EXPRESSION_SETLOOKUPOPTIONS
_QUERYREQUEST_EXPRESSION_CALL.containing_type = _QUERYREQUEST_EXPRESSION
_QUERYREQUEST_EXPRESSION_CALL.oneofs_by_name['options'].fields.append(
  _QUERYREQUEST_EXPRESSION_CALL.fields_by_name['set_lookup_options'])
_QUERYREQUEST_EXPRESSION_CALL.fields_by_name['set_lookup_options'].containing_oneof = _QUERYREQUEST_EXPRESSION_CALL.oneofs_by_name['options']
_QUERYREQUEST_EXPRESSION_SETLOOKUPOPTIONS.containing_type = _QUERYREQUEST_EXPRESSION
_QUERYREQUEST_EXPRESSION.fields_by_name['literal'].message_type = _QUERYREQUEST_EXPRESSION_LITERAL
_QUERYREQUEST_EXPRESSION.fields_by_name['call'].message_type = _QUERYREQUEST_EXPRESSION_CALL
_QUERYREQUEST_EXPRESSION.containing_type = _QUERYREQUEST
_QUERYREQUEST_EXPRESSION.oneofs_by_name['type'].fields.append(
  _QUERYREQUEST_EXPRESSION.fields_by_name['column'])
_QUERYREQUEST_EXPRESSION.fields_by_name['column'].containing_oneof = _QUERYREQUEST_EXPRESSION.oneofs_by_name['type']
_QUERYREQUEST_EXPRESSION.oneofs_by_name['type'].fields.append(
  _QUERYREQUEST_EXPRESSION.fields_by_name['literal'])
_QUERYREQUEST_EXPRESSION.fields_by_name['literal'].containing_oneof = _QUERYREQUEST_EXPRESSION.oneofs_by_name['type']
_QUERYREQUEST_EXPRESSION.oneofs_by_name['type'].fields.append(
  _QUERYREQUEST_EXPRESSION.fields_by_name['call'])
_QUERYREQUEST_EXPRESSION.fields_by_name['call'].containing_oneof = _QUERYREQUEST_EXPRESSION.oneofs_by_name['type']
_QUERYREQUEST.fields_by_name['filter_expression'].message_type = _QUERYREQUEST_EXPRESSION
DESCRIPTOR.message_types_by_name['QueryRequest'] = _QUERYREQUEST
DESCRIPTOR.message_types_by_name['QueryResponse'] = _QUERYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryRequest = _reflection.GeneratedProtocolMessageType('QueryRequest', (_message.Message,), {

  'Expression' : _reflection.GeneratedProtocolMessageType('Expression', (_message.Message,), {

    'Literal' : _reflection.GeneratedProtocolMessageType('Literal', (_message.Message,), {
      'DESCRIPTOR' : _QUERYREQUEST_EXPRESSION_LITERAL,
      '__module__' : 'seqr_query_service_pb2'
      # @@protoc_insertion_point(class_scope:seqr.QueryRequest.Expression.Literal)
      })
    ,

    'Call' : _reflection.GeneratedProtocolMessageType('Call', (_message.Message,), {
      'DESCRIPTOR' : _QUERYREQUEST_EXPRESSION_CALL,
      '__module__' : 'seqr_query_service_pb2'
      # @@protoc_insertion_point(class_scope:seqr.QueryRequest.Expression.Call)
      })
    ,

    'SetLookupOptions' : _reflection.GeneratedProtocolMessageType('SetLookupOptions', (_message.Message,), {
      'DESCRIPTOR' : _QUERYREQUEST_EXPRESSION_SETLOOKUPOPTIONS,
      '__module__' : 'seqr_query_service_pb2'
      # @@protoc_insertion_point(class_scope:seqr.QueryRequest.Expression.SetLookupOptions)
      })
    ,
    'DESCRIPTOR' : _QUERYREQUEST_EXPRESSION,
    '__module__' : 'seqr_query_service_pb2'
    # @@protoc_insertion_point(class_scope:seqr.QueryRequest.Expression)
    })
  ,
  'DESCRIPTOR' : _QUERYREQUEST,
  '__module__' : 'seqr_query_service_pb2'
  # @@protoc_insertion_point(class_scope:seqr.QueryRequest)
  })
_sym_db.RegisterMessage(QueryRequest)
_sym_db.RegisterMessage(QueryRequest.Expression)
_sym_db.RegisterMessage(QueryRequest.Expression.Literal)
_sym_db.RegisterMessage(QueryRequest.Expression.Call)
_sym_db.RegisterMessage(QueryRequest.Expression.SetLookupOptions)

QueryResponse = _reflection.GeneratedProtocolMessageType('QueryResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYRESPONSE,
  '__module__' : 'seqr_query_service_pb2'
  # @@protoc_insertion_point(class_scope:seqr.QueryResponse)
  })
_sym_db.RegisterMessage(QueryResponse)



_QUERYSERVICE = _descriptor.ServiceDescriptor(
  name='QueryService',
  full_name='seqr.QueryService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=751,
  serialized_end=817,
  methods=[
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='seqr.QueryService.Query',
    index=0,
    containing_service=None,
    input_type=_QUERYREQUEST,
    output_type=_QUERYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_QUERYSERVICE)

DESCRIPTOR.services_by_name['QueryService'] = _QUERYSERVICE

# @@protoc_insertion_point(module_scope)
